version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: exampleDB
    ports:
      - "3300:3300"
    volumes:
      - profilecheck_mysqlVolume:/data/db
    
volumes:
  profilecheck_mysqlVolume: